### ISSUE TITLE
Printing the wall list table truncates last two lines.

### ISSUE THREAD

**Issue by vger76** [ffrgo/pairgoth#2] opened 2024-09-23 21:42 UTC
As described in the title. We printed the wall list (standings) to pdf then shared it between rounds for the convenience of players but got complaints that the last two players were either totally missing or half cut off. After a quick look it was obvious that the table was truncated already in the print preview screen. This could be a browser thing (happens on Firefox browser running on Debian 11) publishing standings to an HTML file then printing to pdf then sharing is a bit time consuming.

Thank you!

**Comment by arkanovicz** [comment] 2024-09-26 09:53
This is a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1744363) which has been fixed in firefox v122.

The problem is that even Debian 12 is still using firefox v115. My recommendation is to manually download and install a newer firefox version from [the official download page](https://mozilla.org/firefox/download).

**Closed** 2024-09-26 09:54 UTC
Labels: wontfix

**Comment by vger76** [comment] 2024-09-29 19:37
Thank you for looking into this, and the speedy reply. It won't be a problem till Summer 2025 and exporting the wall list to html then printing to PDF was the quick fix we found. But I'll try and update the browser. Thank you!
